name: react-application-workflow 
on:
    workflow_dispatch:

    pull_request:
        types: [opened, reopened] 

jobs: 
    label-pr:
        name: Label new pr 
        runs-on: ubuntu-latest

        steps:
            - name: label new pull request
              uses: adityadhopade/label_pr_custom_action@v1.0.0
              with: 
                  gh-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
                  label: 'new-pr'

            - name: Label bug fixes
              if: contains(github.event.pull_request.title, 'fix')
              uses: adityadhopade/label_pr_custom_action@v1.0.0
              with:
                  gh-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
                  label: 'bug'
