name: react-application-workflow 
on:
    workflow_dispatch:
    push:
        branches:
               - "main"

jobs: 
    deploy:
        name: deploying to ec2 
        runs-on: ubuntu-server

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Deploy the application
              env:
                  PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIV_KEY }}
                  HOST_NAME: ${{ vars.HOST_DNS }}
                  USER_NAME: ${{ vars.USER_NAME }}

              run: |
                  echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '

                    if [ -d "simple-react-application" ]; then
                      echo "Repo exists already"
                      cd ./simple-react-application || exit 1
                      git checkout main || exit 1
                      git pull origin main
                    else
                      echo "Cloning repository"
                      git clone git@github.com:rakesh-krishnamoorthy/simple-react-application.git || exit 1
                      cd ./simple-react-application || exit 1
                      git checkout main || exit 1
                      git pull origin main
                    fi
                    
                      chmod +x deploy.sh
                      sh deploy.sh
                      '

                

            
            
